### ISSUE TITLE
Undo mirrors

### ISSUE THREAD

**Issue by slashtechno** [jaedle/mirror-to-gitea#13]
Is it possible to remove all repository mirrors at once rather than needing to manually remove every repository mirror?

**Comment by jaedle** [comment]
Hi👋

Thanks for opening the issue.

I guess I am unsure what you are trying to achieve.

Would you mind describing the current state and your desired target state?

This tool fulfils the purpose of auto-creating repositories on a Gitea instance with enabled mirroring from GitHub.

**Comment by slashtechno** [comment]
I don't believe there is a way to mass-delete the repositories made by this script if the mirrors are no longer needed.
I'm curious if a feature could be added to remove all mirrors created by the script.

**Comment by jaedle** [comment]
Sorry for the late response, I was pretty busy due to private reasons.

This script does only create new repositories on a Gitea instance and will setup mirroring. 
The script is not able to detect if a repo was created by itself or any other way.

I would rather recommend to create an automation for your Gitea instance (scripts) instead of adding such a feature.

Deleting existing repositories is a forceful and destructive process which may lead to data loss. 

I can understand your usecase, but I may consider this as not fitting to this small script.

I hope you can understand that decision.

Best,
Dennis

**Comment by slashtechno** [comment]
Thanks for your response.
I agree, adding the option to delete mirrored repositories could be rather destructive in addition to adding unnecessary complexity.
